// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("GitChangeLog.CommandLine")]
[assembly: AssemblyProductAttribute("GitChangeLog")]
[assembly: AssemblyDescriptionAttribute("Extract change logs from git annotated tags")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "GitChangeLog.CommandLine";
        internal const System.String AssemblyProduct = "GitChangeLog";
        internal const System.String AssemblyDescription = "Extract change logs from git annotated tags";
        internal const System.String AssemblyVersion = "0.1.0.0";
        internal const System.String AssemblyFileVersion = "0.1.0.0";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
